// Generate supabase/seed.sql from the JSON data.
// Run: node muscle-map/scripts/generate-seed.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const muscles = JSON.parse(readFileSync(join(root, 'data/muscles.json'), 'utf8')).muscles;
const exercises = JSON.parse(readFileSync(join(root, 'data/exercises.json'), 'utf8')).exercises;

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const arr = (a) => `array[${a.map(q).join(', ')}]::text[]`;

const lines = ['-- Generated by scripts/generate-seed.mjs. Do not edit by hand.', ''];

lines.push('insert into public.muscles (id, name, muscle_group, body_view, bilateral, external_ids) values');
lines.push(
  muscles
    .map((m) => `  (${q(m.id)}, ${q(m.name)}, ${q(m.group)}, ${q(m.view)}, ${m.bilateral}, ${q(JSON.stringify(m.external_ids ?? {}))}::jsonb)`)
    .join(',\n') + '\non conflict (id) do update set name = excluded.name, muscle_group = excluded.muscle_group, body_view = excluded.body_view, bilateral = excluded.bilateral, external_ids = excluded.external_ids;',
);
lines.push('');

lines.push('insert into public.exercises (id, name, category, pattern, equipment, aliases, is_global) values');
lines.push(
  exercises
    .map((e) => `  (${q(e.id)}, ${q(e.name)}, ${q(e.category)}, ${q(e.pattern)}, ${q(e.equipment)}, ${arr(e.aliases ?? [])}, true)`)
    .join(',\n') + '\non conflict (id) do update set name = excluded.name, category = excluded.category, pattern = excluded.pattern, equipment = excluded.equipment, aliases = excluded.aliases;',
);
lines.push('');

lines.push('delete from public.exercise_muscles where exercise_id in (select id from public.exercises where is_global);');
lines.push('insert into public.exercise_muscles (exercise_id, muscle_id, role) values');
const rows = [];
for (const e of exercises) {
  for (const m of e.primary_muscles) rows.push(`  (${q(e.id)}, ${q(m)}, 'primary')`);
  for (const m of e.secondary_muscles) rows.push(`  (${q(e.id)}, ${q(m)}, 'secondary')`);
}
lines.push(rows.join(',\n') + ';');
lines.push('');

writeFileSync(join(root, 'supabase/seed.sql'), lines.join('\n'));
console.log(`wrote supabase/seed.sql: ${muscles.length} muscles, ${exercises.length} exercises, ${rows.length} links`);
